language: go

before_install:
  - go get -t -v ./...
install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - $HOME/gopath/bin/goveralls -service=travis-ci

script:
  - go test ./...

go:
  - 1.6
  - 1.7
  - 1.8
  - tip